baseURL = 'https://melodious-bubblegum-0ccf83.netlify.app/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[outputs]
    home = ["HTML", "JSON"]


[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 30